spring:
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
