logging:
  level:
    root: INFO
spring:
  application:
    name: ecommerce
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration/ddl, classpath:db/migration/dml
springdoc:
  api-docs:
    enabled: false
    path: /api-docs
  swagger-ui:
    enabled: false
